{"name": "Проверка ручки patch, что нельзя поменять данные неаутентифицированного пользователя", "status": "passed", "start": 1732504695004, "stop": 1732504695339, "uuid": "fbb99b3c-8a97-49fb-8a09-94a07807c542", "historyId": "1afabfdefe14d28260cc0836bfbaaee0", "testCaseId": "1afabfdefe14d28260cc0836bfbaaee0", "fullName": "tests.test_changing_user.TestChangingUser#test_update_user_unauthenticated_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_changing_user"}, {"name": "subSuite", "value": "TestChangingUser"}, {"name": "host", "value": "DESKTOP-ME9CEU9"}, {"name": "thread", "value": "2972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_changing_user"}]}